version: '3.6'

services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    restart: unless-stopped
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=password
      - DOCKER_INFLUXDB_INIT_ORG=neutra
      - DOCKER_INFLUXDB_INIT_BUCKET=uniswap-v3-test
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=V2-token==
    ports:
      - 8086:8086
    volumes:
      - ./data/influxdb:/var/lib/influxdb
